FROM node:22-alpine AS build

WORKDIR /src

COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM build AS production
COPY --from=build /src/.next ./.next
COPY --from=build /src/node_modules ./node_modules

CMD npm run start
