import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "time sheet thingy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>


        <div className='head'>
          
          <div className='headBtn'>
            logout
          </div>
          {/*we will put a header here*/}
        </div>
        
        {children}


        <div className='foot'>
          {/*we will put a footer here*/}
        </div>
        
      </body>
    </html>
  );
}
